version: "3"

services:
  my-budget-db:
    image: postgres
    networks:
      - my-budget-network
    ports:
      - 5432:5432
    volumes:
      - /var/lib/docker/volumes/my-budget-db-volume/_data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: my-budget_db

  teamcity-db:
    image: postgres
    networks:
      - my-budget-network
    ports:
      - 5433:5433
    volumes:
      - /var/lib/docker/volumes/teamcity-db-volume/_data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: teamcity_db

  teamcity-server:
    image: jetbrains/teamcity-server
    networks:
      - my-budget-network
    ports:
      - 8111:8111
    volumes:
      - /var/lib/docker/volumes/teamcity-volume/_data:/data/teamcity_server/datadir
      - /var/lib/docker/volumes/teamcity-logs-volume/_data:/opt/teamcity/logs
    depends_on:
      - teamcity-db
    container_name: teamcity_server

networks:
  my-budget-network:

volumes:
  teamcity-volume:

  teamcity-logs-volume:

  teamcity-db-volume:

  my-budget-db-volume:
